# Generated by Django 5.0.2 on 2024-10-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantation',
            name='established_date',
        ),
        migrations.AlterField(
            model_name='plantation',
            name='status',
            field=models.CharField(choices=[('yahshi', 'Yahshi'), ('ortacha', 'Ortacha'), ('yomon', 'Yomon')], default='yahshi', max_length=7),
        ),
    ]
