# Generated by Django 5.0.2 on 2024-10-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_plantation_established_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.CharField(choices=[('tashkent_city', 'Ташкент (город)'), ('tashkent', 'Ташкентская область'), ('andijan', 'Андижанская область'), ('bukhara', 'Бухарская область'), ('djizzakh', 'Джиззакская область'), ('fergana', 'Ферганская область'), ('kashkadarya', 'Кашкадарьинская область'), ('khorezm', 'Хорезмская область'), ('namangan', 'Наманганская область'), ('navoiy', 'Навоийская область'), ('samarkand', 'Самаркандская область'), ('sirdarya', 'Сырдарьинская область'), ('surkhandarya', 'Сурхандарьинская область'), ('karakalpakstan', 'Республика Каракалпакстан')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
