# Generated by Django 5.0.2 on 2024-10-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_news_images_newsimage_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
