# Generated by Django 5.0.2 on 2024-10-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ServiceReview',
        ),
    ]
