# Generated by Django 5.0.2 on 2024-10-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_review_servicereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='link',
            new_name='link_to_full',
        ),
    ]
